======================================================================
Thu Feb 28 11:27:09 EST 2019

   p3 measure.py 
running deeplab on image
resized_image.shape:   
(513, 162, 3)




resized_image going into deeplab




Traceback (most recent call last):
  File "measure.py", line 639, in <module>
    test_chest_circ()
  File "measure.py", line 619, in test_chest_circ
    chest_circ=chest_circum(json_fname,front_fname,side_fname, NATHAN_H)
  File "measure.py", line 305, in chest_circum
    pix_height    = pix_h(front_mask)
  File "measure.py", line 554, in pix_h
    return pixel_height(mask)
  File "measure.py", line 551, in pixel_height
    return np.amax(locs[0])-np.amin(locs[0])
  File "/home/n/anaconda3/envs/cat/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2334, in amax
    initial=initial)
  File "/home/n/anaconda3/envs/cat/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 83, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity









  These aren't precisely "bugs," but records of why measure.py doesn't work yet:

  1.  Nipple-height-finding doesn't quite work.
    a.  Ideal solution involves a Conv neural network trained on labeled locations of people's nipples
      1.  And then a vertical shift from the front view to the size view (ie. bottoms of feet should be at same height)
        a.  The vertical shift ought to be more subtly tuned than I was doing earlier.  Perhaps the center of the top and bottom should be in the same place.
    b.  Oh wait but also women can't do that.  Unless we want bust size ON TOP of the breasts.  Hm.  Maybe for clothes that actually IS what we want.
  2.  The assumption that chest circumference is exactly an ellipse overshoots the actual chest measurement.
    a.  Solve by adding a constant?
  3.
  4.
  5.
  6.
  7.
  8.
  9.
  10.
  11.
  12.
  13.
  14.
  15.
  16.
  17.
  18.



















======================================================================
Wed Feb 27 10:46:38 EST 2019

  Before going into pltshow, I get this bug (seg.py's segment_nparr(self, img), right before the return statement): 

  resized_image going into deeplab
  Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
  saving segmentation map in  _segmented____binary_mask_.jpg
  WARNING:root:Lossy conversion from int64 to uint8. Range [0, 15]. Convert image to uint8 prior to saving to suppress this warning.

